- name: Create docker registry and push container to it
  hosts: localhost
  tasks:
    - name: Create ecr in AWS
      ecs_ecr:
        name: simple_sinatra_app_1
        region: ap-southeast-2
        state: present
      register: ecr
    - name: get command for login
      shell: "aws ecr get-login --region ap-southeast-2 --no-include-email"
      args:
        executable: /bin/bash
      register: login
    - name: docker login
      shell: "{{ login.stdout }}"
      args:
        executable: /bin/bash
    - name: docker build
      docker_image:
        path: ./
        name: simple_sinatra_app
    - name: docker push
      docker_image:
        name: "{{ ecr.repository.repositoryUri }}"
        push: yes
    - name: Create VPC
      ec2_vpc_net:
        name: sinatra
        cidr_block: 10.0.0.0/16
        region: ap-southeast-2
      register: vpc
      tags:
        - ecs
    - debug:
        var: vpc
    - name: Create subnet for cluster
      ec2_vpc_subnet:
        az: ap-southeast-2a
        cidr: 10.0.0.0/24
        vpc_id: "{{ vpc.vpc.id }}"
        state: present
        resource_tags:
          Name: sinatra_subnet
      register: sinatra_subnet
    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: ap-southeast-2
        state: present
    - name: Create ECS cluster
      ecs_cluster:
        name: simple-sinatra-webserver
        state: present
    - name: Create an autoscaling group launch configuration
      ec2_lc:
        name: sinatra_lc
        region: ap-southeast-2
        assign_public_ip: yes
        instance_type: t2.medium
        instance_profile_name: ecsInstanceRole
        image_id: "ami-0a7936ea6d7d16c6d"
    - name: Create an autoscaling group
      ec2_asg:
        name: sinatra_asg
        region: ap-southeast-2
        min_size: 1
        max_size: 2
        vpc_zone_identifier: [ "{{ sinatra_subnet.id }}" ]
        launch_config_name: sinatra_lc
    - name: Create task to spin up web server
      ecs_taskdefinition:
        containers:
        - name: sinatra
          cpu: 128
          essential: true
          image: "{{ ecr.repository.repositoryUri }}:latest"
          memory: 1024
          portMappings:
          - containerPort: 9292
            hostPort: 80
        launch_type: EC2
        region: ap-southeast-2
        family: simple-sinatra-webserver
        state: present
      register: task_output
      tags:
        - taskdef
    - name: Create and spin up ECS service
      ecs_service:
        name: simple-ecs
        state: present
        cluster: simple-sinatra-webserver
        task_definition: "simple-sinatra-webserver:1"
        desired_count: 1
      tags:
        - ecs-server
    - name: Start task
      ecs_task:
        operation: run
        region: ap-southeast-2
        cluster: simple-sinatra-webserver
        task_definition: simple-sinatra-webserver
        started_by: ansible
        count: 1
      tags:
        - task-run