- name: Create docker registry and push container to it
  hosts: localhost
  tasks:
    - name: create ecr in AWS
      ecs_ecr:
        name: simple_sinatra_app_1
        region: ap-southeast-2
        state: present
