- name: Create docker registry and push container to it
  hosts: localhost
  tasks:
    - name: Delete all containers within simple_sinatra_app_1 ECR repo
      shell: aws ecr batch-delete-image --repository-name simple_sinatra_app_1 --image-ids imageTag=latest
      args:
        executable: /bin/bash
    - name: Destroy ecr with same name if exists
      ecs_ecr:
        name: simple_sinatra_app_1
        state: absent
    - name: Create ecr in AWS
      ecs_ecr:
        name: simple_sinatra_app_1
        region: ap-southeast-2
        state: present
      register: ecr
    - name: get command for login
      shell: "aws ecr get-login --region ap-southeast-2 --no-include-email"
      args:
        executable: /bin/bash
      register: login
    - name: docker login
      shell: "{{ login.stdout }}"
      args:
        executable: /bin/bash
    - name: docker build
      docker_image:
        path: ./
        name: simple_sinatra_app
    - name: docker push
      docker_image:
        name: "{{ ecr.repository.repositoryUri }}"
        push: yes
    - name: Create VPC
      ec2_vpc_net:
        name: sinatra
        cidr_block: 10.0.0.0/16
        region: ap-southeast-2
      register: vpc
      tags:
        - ecs
    - name: Create subnet for cluster
      ec2_vpc_subnet:
        az: ap-southeast-2a
        cidr: 10.0.0.0/24
        vpc_id: "{{ vpc.vpc.id }}"
        state: present
        resource_tags:
          Name: sinatra_subnet
      register: sinatra_subnet
      tags:
        - ecs
    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: ap-southeast-2
        state: present
      tags:
        - ecs
    - name: Create task to spin up web server
      ecs_taskdefinition:
        containers:
        - name: sinatra
          cpu: 128
          essential: true
          image: 685433754787.dkr.ecr.ap-southeast-2.amazonaws.com/simple_sinatra_app_1:latest
          memory: 1024
          portMappings:
          - containerPort: 9292
            hostPort: 80
        launch_type: EC2
        region: ap-southeast-2
        family: simple-sinatra-webserver
        state: present
      register: task_output
      tags:
        - taskdef
    - name: Start task in existing cluster
      ecs_task:
        cluster: ec2
        task_definition: simple-sinatra-app
        count: 1
        started_by: ansible_user
        operation: run
      tags:
        - taskrun
    - name: Create ECS EC2 cluster
      ecs_service:
        name: simple-sinatra-app-1
        desired_count: 1
        launch_type: EC2
        task_definition: "simple-sinatra-app:2"
        state: present
      tags:
        - ecs
