- name: Create docker registry and push container to it
  hosts: localhost
  tasks:
    - name: Destroy ecr with same name if exists
      ecs_ecr:
        name: simple_sinatra_app_1
        state: absent
    - name: Create ecr in AWS
      ecs_ecr:
        name: simple_sinatra_app_1
        region: ap-southeast-2
        state: present
      register: ecr
    - name: docker login
      shell: "aws ecr get-login --region ap-southeast-2 --no-include-email"
      args:
        executable: /bin/bash
    - name: docker build
      docker_image:
        path: ./
        name: simple_sinatra_app
        tag: simple_sinatra_app
